---

  - name: ensure the original packed file is gone
    file: 
      path:  "{{ packed_template_path }}" 
      state: absent

  - name: pack the domain
    command: "{{ mw_home }}/oracle_common/common/bin/pack.sh -domain {{ domain_home }} -managed true -template {{ packed_template_path }}/{{ packed_template_name }}.jar -template_name {{ packed_template_name }}"

  - name: bring the template over
    fetch: 
      src:  "{{ packed_template_path }}/{{ packed_template_name }}.jar" 
      dest: /tmp/{{ packed_template_name }}.jar
      flat: yes 
